### ISSUE TITLE
Does not work on version 1.8.9

### ISSUE THREAD

**Issue by xOxXakerxOx** [flathub/io.gdevs.GDLauncher#19]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 06.07.21 17:52
Description: Initializing game

java.lang.ExceptionInInitializerError
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.12.14-1-MANJARO
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 269362288 bytes (256 MB) / 324534272 bytes (309 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xmx4096m -Xms4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

**Comment by nickavem** [comment]
1. Can you reproduce this with the app image version provided by the GDLauncher upstream?

2. What graphics chip do you use?

**Comment by xOxXakerxOx** [comment]
>     1. Can you reproduce this with the app image version provided by the GDLauncher upstream?
> 
>     2. What graphics chip do you use?

1. Minecraft versions higher than 1.12.2 work 
2. Nvidia GeForce GTX 1060

**Comment by nickavem** [comment]
Do you get the same crash when using the app image version (check this repo's readme for a quick guide)

**Comment by xOxXakerxOx** [comment]
> Do you get the same crash when using the app image version (check this repo's readme for a quick guide)

Minecraft 1.8.9 was enabled via the app image version

**Comment by nickavem** [comment]
@xOxXakerxOx please test the build from the linked PR once it is finished working to see if it resolves your issue.

**Comment by xOxXakerxOx** [comment]
> @xOxXakerxOx please test the build from the linked PR once it is finished working to see if it resolves your issue.

I will be able to check only in 3 weeks, right now I'm not at home.

**Comment by nickavem** [comment]
Alright. I'm 99% sure this addresses the issue you were referencing, so will merge and close, but you are welcome to reopen if I was wrong.

**Comment by xOxXakerxOx** [comment]
> Alright. I'm 99% sure this addresses the issue you were referencing, so will merge and close, but you are welcome to reopen if I was wrong.

I checked it, it works
