### ISSUE TITLE
Instances location

### ISSUE THREAD

**Issue by tommytran732** [flathub/io.gdevs.GDLauncher#20]
This is not a major issue, but I notice that the data for the installation is inside of /home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/instances/ instead of /home/user/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/data

I think this is a bit weird, as flatpak apps typically save their data inside of the data and not config directory... Maybe you could look into moving the instances into the data directory?

**Comment by nickavem** [comment]
While I could implement this, it would be more beneficial for upstream to simply implement [this specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by nickavem** [comment]
I would move this issue upstream.
