### ISSUE TITLE
update to v1.1.21

### ISSUE THREAD

**Issue by cobalt2727** [flathub/io.gdevs.GDLauncher#37]
[The current release](https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.1.21) has been out since January - could we see an update to this package? v.1.1.22 is probably releasing soon, too

**Comment by nickavem** [comment]
Sorry, it should have be updating automatically with the upstream AppImage.

I will update it manually and look into it later today when I get a chance.

**Comment by nickavem** [comment]
#38

**Comment by nickavem** [comment]
Metadata still seems to be broken. @barthalion @bilelmoussaoui, do you know what's wrong?
