### ISSUE TITLE
Add Game tag

### ISSUE THREAD

**Issue by LeSnake04** [flathub/io.gdevs.GDLauncher#39]
Adding the game tag will make this program available in [athenium](https://gitlab.com/librebob/athenaeum)

**Comment by nickavem** [comment]
While this is a Libre front end, and everything within the package is Libre, I would not consider it a "Libre Game". But @librebob can give his opinion before I close.

**Comment by LeSnake04** [comment]
While I have a similar opnion, these open source launchers are already listed there:
* Polymc
* Jdlauncher
* Atlauncher
* and probably more

So GDlauncher should join them IMO.
